/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafkita;

import java.time.Duration;
import org.junit.Test;

public class KafkitaTest {

  @Test
  public void testBasic() throws Exception {
    Kafkita.main(new String[] {"stack", "-noWait"});
    Kafkita.zkServices.get(Kafkita.DEFAULT_STACK_NAME).stop(Duration.ofSeconds(5));
    Kafkita.kafkaServices.get(Kafkita.DEFAULT_STACK_NAME).stop(Duration.ofSeconds(5));
  }
}
